controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

#  arm_trajectory_controller:
#    type: effort_controllers/JointTrajectoryController
#    joints:
#      - joint1
#      - joint2
#      - joint3
#      - joint4
#      - joint5
#      - joint6
#      - joint7
#    gains:
#      joint1: { p: 15.0, i: 0.2, d: 4.0, i_clamp_max: 1., i_clamp_min: -1., antiwindup: true, publish_state: true }
#      joint2: { p: 50.0, i: 2.0, d: 5.0, i_clamp_max: 1., i_clamp_min: -1., antiwindup: true, publish_state: true }
#      joint3: { p: 15.0, i: 0.5, d: 4.0, i_clamp_max: 2.5, i_clamp_min: -2.5, antiwindup: true, publish_state: true }
#      joint4: { p: 50.0, i: 2.0, d: 5.0, i_clamp_max: 1, i_clamp_min: -1, antiwindup: true, publish_state: true }
#      joint5: { p: 3.0, i: 0.1, d: 0.3, i_clamp_max: 0.5, i_clamp_min: -1, antiwindup: true, publish_state: true }
#      joint6: { p: 3.0, i: 0.1, d: 0.3, i_clamp_max: 0.8, i_clamp_min: -0.5, antiwindup: true, publish_state: true }
#      joint7: { p: 0.5, i: 0.1, d: 0.02, i_clamp_max: 0.5, i_clamp_min: -0.5, antiwindup: true, publish_state: true }

  arm_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
      - joint7