swingarm_hw:
  loop_frequency: 500
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  bus:
    - can0

  devices:
    - name: "joint1_motor"
      bus: "can0"
      id: 0x001
      model: "dm4340"
    - name: "joint2_motor"
      bus: "can0"
      id: 0x002
      model: "dm4340"
    - name: "joint3_motor"
      bus: "can0"
      id: 0x003
      model: "dm4340"
    - name: "joint4_motor"
      bus: "can0"
      id: 0x004
      model: "dm4340"
    - name: "joint5_motor"
      bus: "can0"
      id: 0x005
      model: "dm4310"
    - name: "joint6_motor"
      bus: "can0"
      id: 0x006
      model: "dm4310"
    - name: "joint7_motor"
      bus: "can0"
      id: 0x007
      model: "dm4310"