controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 100

#  gripper_controller:
#    type: hybrid_controllers/gripperController
#    joint: left_gripper_joint

  gripper_controller:
    type: effort_controllers/JointPositionController
    joint: left_gripper_joint
    pid: { p: 3000.0, i: 500., d: 1000.0, i_clamp_max: 800.0, i_clamp_min: -800.0, antiwindup: false, publish_state: false }

  imu_sensor_controller:
    type: imu_sensor_controller/ImuSensorController
    publish_rate: 50

#  button_position_controller:
#    type: button_position_controller/ButtonPositionController
#    joint: left_gripper_joint
#    button_panel: button_panel
#    position_a: 0.5   # 目标位置A（弧度）
#    position_b: 2.0   # 目标位置B（弧度）
#    p_gain: 100.0     # 比例增益
#    i_gain: 0.1       # 积分增益
#    d_gain: 10.0      # 微分增益
