swingarm_hw:
  loop_frequency: 500
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  bus:
    - can0

  devices:
    - name: "left_gripper_joint_motor"
      bus: "can0"
      id: 0x008
      model: "dm4310"