swingarm_hw:
  loop_frequency: 500
  cycle_time_error_threshold: 0.001
  thread_priority: 95
  bus:
    - can0

  devices:
    - name: "left_gripper_joint_motor"
      bus: "can0"
      id: 0x008
      model: "dm4310"
    - name: "button_panel"
      bus: "can0"
      id: 0x200
      model: "button_panel_50"
    - name: "left_gripper_imu"
      bus: "can0"
      id: 0x101
      model: "st_imu"
      config:
        orientation_covariance_diagonal: [ 0.0012, 0.0012, 0.0012 ]
        angular_velocity_covariance: [ 0.0004, 0.0004, 0.0004 ]
        linear_acceleration_covariance: [ 0.01, 0.01, 0.01 ]
        angular_vel_offset: [ -0.002433065, 0.003094675, 0.003542005 ]
        angular_vel_coeff: 0.0010652644
        accel_coeff: 0.0017944335
        temp_coeff: 0.125
        temp_offset: 23.0
        filter: complementary
        do_bias_estimation: false
        do_adaptive_gain: true
        gain_acc: 0.0003
